apiVersion: apps/v1
kind: Deployment
metadata:
  name: emp-portal-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: emp-portal
  template:
    metadata:
      labels:
        app: emp-portal
    spec:
      containers:
        - name: emp-portal-container
          image: 942580909312.dkr.ecr.us-east-1.amazonaws.com/emp-portal:latest
          ports:
            - containerPort: 5000
